"""empty message

Revision ID: 00adcedd6bdb
Revises: b16ca713cd0a
Create Date: 2021-11-09 23:10:54.077592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00adcedd6bdb'
down_revision = 'b16ca713cd0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'downvotes')
    op.drop_column('pitches', 'upvotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('upvotes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pitches', sa.Column('downvotes', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
