"""Add upvotes and downvotes

Revision ID: b16ca713cd0a
Revises: 40fae0de9e14
Create Date: 2021-11-08 09:39:56.108858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16ca713cd0a'
down_revision = '40fae0de9e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('upvotes', sa.Integer(), nullable=False))
    op.add_column('pitches', sa.Column('downvotes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'downvotes')
    op.drop_column('pitches', 'upvotes')
    # ### end Alembic commands ###
